#!/usr/bin/env bash

DOCKER_BIN=$(which docker)
if [ -z "$DOCKER_BIN" ]
    then
    echo "We can't find the docker executable. Docker is required for this build process"
    exit
fi

OPENJDK_IMAGE=$(docker images openjdk -q)
if [ -z "$OPENJDK_IMAGE" ]
    then
    echo "You need to pull down the openjdk docker image for this build"
    echo "Pull down now? (y/n)"
    read PULLJDK
    if [ "$PULLJDK" = "y" ] || [ "$PULLJDK" = "Y" ]
        then
        docker pull openjdk
    else
        exit
    fi
fi

GRADLE_IMAGE=$(docker images gradlebox -q)
if [ -z "$GRADLE_IMAGE" ]
    then
    echo "You need to build the gradle box docker image for this build"
    echo "Build now? (y/n)"
    read BUILDGRADLEBOX
    if [ "$BUILDGRADLEBOX" = "y" ] || [ "$BUILDGRADLEBOX" = "Y" ]
        then
        docker build docker/gradlebox/ -t gradlebox
    else
        exit
    fi
fi

BUILDER_IMAGE=$(docker images formigiobuilder -q)
if [ -z "$BUILDER_IMAGE" ]
    then
    echo "You need to build the formigio builder box docker image for this build"
    echo "Build now? (y/n)"
    read BUILDERBOX
    if [ "$BUILDERBOX" = "y" ] || [ "$BUILDERBOX" = "Y" ]
        then
        docker build . -t formigiobuilder -f FormigioBuildDockerfile
    else
        exit
    fi
fi

# TESTINGPARAM=""
# echo "Run without tests? (y/n)"
# read SKIPTESTS
# if [ "$SKIPTESTS" = "y" ]
#     then
#     TESTINGPARAM="-x test"
# fi

echo "Building the Java App Jar file... "

docker run -v $(pwd):/var/service -w="/var/service" formigiobuilder gradle clean build

echo "Building the Docker Image... "

docker build "." -t commitr_service:latest