{
"swagger": "2.0",
"info": {
"description": "Api Documentation",
"version": "1.0",
"title": "Api Documentation",
"termsOfService": "urn:tos",
"contact": {},
"license": {
"name": "Apache 2.0",
"url": "http://www.apache.org/licenses/LICENSE-2.0"
}
},
"host": "localhost:8080",
"basePath": "/",
"tags": [
{
"name": "task-controller",
"description": "Task Controller"
},
{
"name": "team-controller",
"description": "Team Controller"
},
{
"name": "goal-controller",
"description": "Goal Controller"
},
{
"name": "invite-controller",
"description": "Invite Controller"
}
],
"paths": {
"/goal": {
"post": {
"tags": [
"goal-controller"
],
"summary": "setGoal",
"operationId": "setGoalUsingPOST",
"consumes": [
"application/json"
],
"produces": [
"*/*"
],
"parameters": [
{
"in": "body",
"name": "goal",
"description": "goal",
"required": true,
"schema": {
"$ref": "#/definitions/Goal"
}
}
],
"responses": {
"201": {
"description": "Created",
"schema": {
"$ref": "#/definitions/Goal"
}
},
"401": {
"description": "Unauthorized"
},
"403": {
"description": "Forbidden"
},
"404": {
"description": "Not Found"
}
}
}
},
"/invite": {
"get": {
"tags": [
"invite-controller"
],
"summary": "getInviteByGoal",
"operationId": "getInviteByGoalUsingGET",
"consumes": [
"application/json"
],
"produces": [
"*/*"
],
"parameters": [
{
"name": "goal",
"in": "query",
"description": "goal",
"required": true,
"type": "string"
}
],
"responses": {
"200": {
"description": "OK",
"schema": {
"$ref": "#/definitions/Invite"
}
},
"401": {
"description": "Unauthorized"
},
"403": {
"description": "Forbidden"
},
"404": {
"description": "Not Found"
}
}
},
"post": {
"tags": [
"invite-controller"
],
"summary": "createInvite",
"operationId": "createInviteUsingPOST",
"consumes": [
"application/json"
],
"produces": [
"*/*"
],
"parameters": [
{
"in": "body",
"name": "invite",
"description": "invite",
"required": true,
"schema": {
"$ref": "#/definitions/Invite"
}
}
],
"responses": {
"201": {
"description": "Created",
"schema": {
"$ref": "#/definitions/Invite"
}
},
"401": {
"description": "Unauthorized"
},
"403": {
"description": "Forbidden"
},
"404": {
"description": "Not Found"
}
}
}
},
"/task": {
"get": {
"tags": [
"task-controller"
],
"summary": "getTasksByGoal",
"operationId": "getTasksByGoalUsingGET",
"consumes": [
"application/json"
],
"produces": [
"*/*"
],
"parameters": [
{
"name": "goal",
"in": "query",
"description": "goal",
"required": true,
"type": "string"
}
],
"responses": {
"200": {
"description": "OK",
"schema": {
"type": "array",
"items": {
"$ref": "#/definitions/Task"
}
}
},
"401": {
"description": "Unauthorized"
},
"403": {
"description": "Forbidden"
},
"404": {
"description": "Not Found"
}
}
},
"post": {
"tags": [
"task-controller"
],
"summary": "createTask",
"operationId": "createTaskUsingPOST",
"consumes": [
"application/json"
],
"produces": [
"*/*"
],
"parameters": [
{
"in": "body",
"name": "dto",
"description": "dto",
"required": true,
"schema": {
"$ref": "#/definitions/Task"
}
}
],
"responses": {
"201": {
"description": "Created",
"schema": {
"$ref": "#/definitions/Task"
}
},
"401": {
"description": "Unauthorized"
},
"403": {
"description": "Forbidden"
},
"404": {
"description": "Not Found"
}
}
},
"put": {
"tags": [
"task-controller"
],
"summary": "updateTask",
"operationId": "updateTaskUsingPUT",
"consumes": [
"application/json"
],
"produces": [
"*/*"
],
"parameters": [
{
"in": "body",
"name": "dto",
"description": "dto",
"required": true,
"schema": {
"$ref": "#/definitions/Task"
}
}
],
"responses": {
"200": {
"description": "OK"
},
"201": {
"description": "Created"
},
"401": {
"description": "Unauthorized"
},
"403": {
"description": "Forbidden"
},
"404": {
"description": "Not Found"
}
}
}
},
"/team": {
"get": {
"tags": [
"team-controller"
],
"summary": "getTeamByIdentity",
"operationId": "getTeamByIdentityUsingGET",
"consumes": [
"application/json"
],
"produces": [
"*/*"
],
"parameters": [
{
"name": "identity",
"in": "query",
"description": "identity",
"required": true,
"type": "string"
}
],
"responses": {
"200": {
"description": "OK",
"schema": {
"type": "array",
"items": {
"$ref": "#/definitions/Team"
}
}
},
"401": {
"description": "Unauthorized"
},
"403": {
"description": "Forbidden"
},
"404": {
"description": "Not Found"
}
}
},
"post": {
"tags": [
"team-controller"
],
"summary": "createTeam",
"operationId": "createTeamUsingPOST",
"consumes": [
"application/json"
],
"produces": [
"*/*"
],
"parameters": [
{
"in": "body",
"name": "team",
"description": "team",
"required": true,
"schema": {
"$ref": "#/definitions/Team"
}
}
],
"responses": {
"201": {
"description": "Created",
"schema": {
"$ref": "#/definitions/Team"
}
},
"401": {
"description": "Unauthorized"
},
"403": {
"description": "Forbidden"
},
"404": {
"description": "Not Found"
}
}
},
"put": {
"tags": [
"team-controller"
],
"summary": "updateTeam",
"operationId": "updateTeamUsingPUT",
"consumes": [
"application/json"
],
"produces": [
"*/*"
],
"parameters": [
{
"in": "body",
"name": "team",
"description": "team",
"required": true,
"schema": {
"$ref": "#/definitions/Team"
}
}
],
"responses": {
"200": {
"description": "OK",
"schema": {
"$ref": "#/definitions/Team"
}
},
"201": {
"description": "Created"
},
"401": {
"description": "Unauthorized"
},
"403": {
"description": "Forbidden"
},
"404": {
"description": "Not Found"
}
}
}
}
},
"definitions": {
"Goal": {
"type": "object",
"properties": {
"guid": {
"type": "string"
},
"team": {
"type": "string"
},
"title": {
"type": "string"
}
}
},
"Task": {
"type": "object",
"properties": {
"completed": {
"type": "boolean"
},
"goal": {
"type": "string"
},
"guid": {
"type": "string"
},
"title": {
"type": "string"
}
}
},
"Team": {
"type": "object",
"properties": {
"identity": {
"type": "string"
},
"title": {
"type": "string"
},
"uuid": {
"type": "string"
}
}
},
"Invite": {
"type": "object",
"properties": {
"goal": {
"type": "string"
},
"guid": {
"type": "string"
}
}
}
}
}