spring:
  profiles.active: local
---
spring:
  profiles: local
  jpa:
    database: hsql
    hibernate:
      ddl-auto: create-drop
    show-sql: true
---
spring:
  profiles: prod
  jpa:
    database: hsql
    hibernate:
      ddl-auto: update
    show-sql: false  