spring:
  profiles.active: local
---
spring:
  profiles: local
  jpa:
    database: hsql
    hibernate:
      ddl-auto: create-drop
    show-sql: true
google:
  client:
    access-token-uri: https://www.googleapis.com/oauth2/v4/token
    user-authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
    scope: https://www.googleapis.com/auth/userinfo.profile
    client-id: 158401991784-9gglr73fn99o0bi4mk8a969pjm6ihaeb.apps.googleusercontent.com
    client-secret: 4wWtC8Zd-N60f8ll_QTYAIrY
  resource:
    user-info-uri: https://www.googleapis.com/oauth2/v1/userinfo
server:
  session:
    persistent: false
---
spring:
  profiles: prod
  datasource:
    url: jdbc:hsqldb:file:/var/hsqldb/data/formigio-db
  jpa:
    database: hsql
    hibernate:
      ddl-auto: update
    show-sql: false  