spring:
  profiles.active: local
---
spring:
  profiles: local
  jpa:
    database: hsql
    hibernate:
      ddl-auto: create-drop
    show-sql: true
basic-auth:
  username: basic
  password: HHH000397
---
spring:
  profiles: prod
  datasource:
    url: jdbc:hsqldb:file:/var/hsqldb/data/formigio-db
  jpa:
    database: hsql
    hibernate:
      ddl-auto: update
    show-sql: false  